### ISSUE TITLE
Setting Service links results in "cannot unmarshal !!map into []string " error

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1160]
Rancher compose version - V0.1.1

docker-compose.yml  used:
```
service1:
  ports:
  - 4444:22/tcp
  tty: true
  image: sangeetha/testclient
  links:
    service2: linkme
  stdin_open: true
service2:
  tty: true
  image: sangeetha/testlbsd
  stdin_open: true

```
Error seen when trying to use it with ./rancher-compose_linux-amd64 -p san1 up
INFO[0000] Creating environment san1                    
ERRO[0000] Failed to parse service service1: yaml: unmarshal errors:
  line 3: cannot unmarshal !!map into []string 
FATA[0000] Could not parse config for project san1 : yaml: unmarshal errors:
  line 3: cannot unmarshal !!map into []string 
sangeethahariharan1@sangee01:~$

 I removed the service name link and i still cannot get it to work:

sangeethahariharan1@sangee01:~$ ./rancher-compose_linux-amd64 -p san1 up
ERRO[0000] Failed to parse service service1: yaml: unmarshal errors:
  line 2: cannot unmarshal !!str `service2` into []string 
FATA[0000] Could not parse config for project san1 : yaml: unmarshal errors:
  line 2: cannot unmarshal !!str `service2` into []string 
```
sangeethahariharan1@sangee01:~$ cat docker-compose.yml
service1:
  ports:
  - 4444:22/tcp
  tty: true
  image: sangeetha/testclient
  links:
    service2
  stdin_open: true
service2:
  tty: true
  image: sangeetha/testlbsd
  stdin_open: true
sangeethahariharan1@sangee01:~$ 
```

**Comment by sangeethah** [comment]
I see the same error when trying to create Lb services as well , since we use links.

sangeethahariharan1@sangee01:~$ ./rancher-compose_linux-amd64 -p lbrancher up
INFO[0000] Creating environment lbrancher               
ERRO[0000] Failed to parse service lb123: yaml: unmarshal errors:
  line 3: cannot unmarshal !!map into []string 
FATA[0000] Could not parse config for project lbrancher : yaml: unmarshal errors:
  line 3: cannot unmarshal !!map into []string 
sangeethahariharan1@sangee01:~$ cat rancher-compose.yml 
lb123:
  scale: 1
  load_balancer_config:
    lb_cookie_stickiness_policy: null
    description: lb123
    name: lb123 config
    app_cookie_stickiness_policy: null
    health_check:
      port: null
      interval: 2000
      unhealthy_threshold: 3
      request_line: GET /name.html HTTP/1.0
      healthy_threshold: 2
      response_timeout: 2000
test1:
  scale: 1
test2:
  scale: 2
sangeethahariharan1@sangee01:~$ cat docker-compose.yml 
lb123:
  ports:
  - 9797:80
  tty: true
  image: rancher/load-balancer-service
  links:
    test1: test1
    test2: test2
  stdin_open: true
test1:
  restart: 'no'
  tty: true
  image: sangeetha/testlbsd
  stdin_open: true
test2:
  restart: 'no'
  tty: true
  image: sangeetha/testlbsd
  stdin_open: true

**Comment by deniseschannon** [comment]
@ibuildthecloud In Rancher Compose, links needs to change from slice into Maporslice if you want to support Map as well as slice for links. 

I can make updated to Rancher Compose/OS, but don't know how to start for updates in Rancher.

**Comment by deniseschannon** [comment]
Created a PR to make changes in rancher-compose, but not in other repos.

**Comment by sangeethah** [comment]
Rancher compose version - V0.1.1

Scenario 1 - service links
docker-compose.yml used:
```
testweb:
  tty: true
  image: sangeetha/testlbsd
  stdin_open: true
testcp:
  ports:
  - 9999:22/tcp
  restart: 'no'
  tty: true
  image: sangeetha/testclient
  links:
    testweb: linkme
  stdin_open: true
```
I am able to create services that are linked using the above docker-compose.yml which was generated from the rancher server. service link name from container in testcp resolve to container in testweb as expected.

Scenario 2  - LB services

Able to get an lb service working with the following docker-compose.yml and rancher-compose.yml that was generated from rancher server:
```
docker-compose.yml
test1:
  tty: true
  image: sangeetha/testlbsd
  stdin_open: true
lb456:
  ports:
  - 7777:80
  tty: true
  image: rancher/load-balancer-service
  links:
    test1: test1
    test2: test2
  stdin_open: true
test2:
  tty: true
  image: sangeetha/testlbsd
  stdin_open: true
~                     
rancher-compose.yml

test1:
  scale: 3
lb456:
  scale: 2
  load_balancer_config:
    lb_cookie_stickiness_policy: null
    description: lb456
    name: lb456 config
    app_cookie_stickiness_policy: null
    health_check:
      port: null
      interval: 3000
      unhealthy_threshold: 3
      request_line: GET /name.html HTTP/1.0
      healthy_threshold: 2
      response_timeout: 4000
test2:
  scale: 4
```
