### ISSUE TITLE
DNS resolution fails because of having a space appended to the service link names.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1167]
Rancher compose version - V0.1.1
```
docker-compose.yml used:
sangeethahariharan1@sangee01:~$ cat dns-rancher-compose.yml 
client:
  scale: 1
web1:
  scale: 3
web2:
  scale: 3
sangeethahariharan1@sangee01:~$ cat dns-docker-compose.yml
client:
  restart: 'no'
  tty: true
  image: sangeetha/testclient
  links:
  - "dns123: mydns"
  stdin_open: true
web1:
  tty: true
  image: sangeetha/testlbsd
  stdin_open: true
web2:
  tty: true
  image: sangeetha/testlbsd
  stdin_open: true
dns123:
  image: rancher/dns-service
  links:
  - "web1: web1"
  - "web2: web2"
```
sangeethahariharan1@sangee01:~
The link name is stored as " mydns"  and  dns resolution for "mydns" from the containers in client service  fails. 

mysql> select name from service_consume_map where name is not null;
+---------+
| name    |
+---------+
|  mydns  |
|  web1   |
|  web2   |

/var/lib/cattle/etc/cattle/dns/answers.json
   "10.42.99.26": {
        "client.": ["10.42.99.26"],
        "client.rancher.internal.": ["10.42.99.26"],
        " mydns.": ["10.42.57.139", "10.42.86.119", "10.42.191.142", "10.42.218.204", "10.42.187.237", "10.42.248.28"],
        " mydns.rancher.internal.": ["10.42.57.139", "10.42.86.119", "10.42.191.142", "10.42.218.204", "10.42.187.237", "10.42.248.28"]
    },
