### ISSUE TITLE
health check params configured in rancher-compose is not honored.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1207]
Server Version - Build from master

Used the rancher-compose file below which had health_check enabled to create service.
Service does not have  health checks enabled.

```
sangeethahariharan1@sangee01:~$ cat health-rc.yml
health4:
  scale: 10
  health_check:
    port: 80
    interval: 2000
    unhealthy_threshold: 3
    request_line: GET /name.html HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
health1:
  scale: 5
  health_check:
    port: 80
    interval: 2000
    unhealthy_threshold: 3
    request_line: GET /index.html HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
health3:
  scale: 5
  health_check:
    port: 80
    interval: 2000
    unhealthy_threshold: 3
    request_line: GET /name.html HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
health2:
  scale: 5
  health_check:
    port: 80
    interval: 2000
    unhealthy_threshold: 3
    request_line: GET /index.html HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
sangeethahariharan1@sangee01:~$ 
```
