### ISSUE TITLE
rancher-compose not creating valid configuration from yml

### ISSUE THREAD

**Issue by Rucknar** [rancherio/rancher#1242]
**Summary**
Creating a wordpress project/service, download the config through the GUI. When importing this through rancher-compose (downloaded binary on mac) the services are created as expected however when starting them the containers are continually spun up and then removed before completing in a cycle and the app never builds.

**Config**
The config works however when done through the web interface that drove this, details below of the settings i was using.

docker-compose.yml
```
WordpressTemp:
  restart: 'no'
  environment:
    GLUSTER_PEER: 10.42.28.140,10.42.175.97
    WORDPRESS_DB_HOSTS: rancherdemo.xxxxxxx.eu-west-1.rds.amazonaws.com:3306
    WORDPRESS_DB_PASSWORD: rancherdemo
  tty: true
  image: nixel/rancher-wordpress-ha:latest
  privileged: true
  stdin_open: true
```
rancher-compose.yml
```
WordpressTemp:
  scale: 2
```

**Versions** 
rancher-compose version v0.1.2
Rancher - v0.24.0-rc5

**Notes**
I appreciate i'm using priviledged access on the containers so wondering if it's related to that. I did however have the same issue with some load balancers on a more complex configuration though so not sure it's related to the container as such.

**Comment by deniseschannon** [comment]
There is something that's not allowing the containers on the service to actually start, so the service will be stuck in activating state as it will continually try to start containers until there are 2 running.

On one of the error-ed out containers, can you try viewing the logs before it's removed? It might be helpful to click on "Restore" before the containers gets removed so that you don't have to worry about it being removed from the UI.

**Comment by Rucknar** [comment]
I did try to get the logs but wasn't fast enough, used the restore option to stop the container being created, this worked but the container won't start so i can't view the logs through the UI. 

Viewed the container in the API and spotted this:

```
transitioning": "error",
"transitioningMessage": " : ff7352e9-5bb7-4e68-912e-8ac57c9942cb : Can not start container with no image",
```

Odd as the image is in the compose yml files. I wonder if `:latest` is causing an issue? I've copy/pasted that image name and it builds a lone container just fine.

**Comment by Rucknar** [comment]
I've tried without the :latest at the end but had the same result. Interestingly, this also happens with a slightly more complex compose script and the loadbalancers which are defined as below, again the API showing the same error about not having an image:

```
IWCLoadbalancerWeb:
  scale: 2
  load_balancer_config:
    lb_cookie_stickiness_policy: null
    description: null
    name: IWCLoadbalancerWeb config
    app_cookie_stickiness_policy: null
    health_check:
      port: null
      interval: 2000
      unhealthy_threshold: 3
      request_line: ''
      healthy_threshold: 2
      response_timeout: 2000
```
