### ISSUE TITLE
linked services missing /etc/hosts entry

### ISSUE THREAD

**Issue by jwhitcraft** [rancherio/rancher#1283]
Hello,

I'm testing out the linked services and i've noticed that the environment variables are there, but the entry in `/etc/hosts` is not.

For example, i have this in my docker-compose.yml file

```yml
db:
  labels:
    io.rancher.scheduler.affinity:host_label: name=bbb
  ports:
  - 3306/tcp
  environment:
    MYSQL_DATABASE: aaa
    MYSQL_PASSWORD: aaa
    MYSQL_ROOT_PASSWORD: aaaa
    MYSQL_USER: aaa
  image: mysql:5.6
redis:
  labels:
    io.rancher.scheduler.affinity:host_label: name=bbb
  ports:
  - 6379/tcp
  image: redis
aaa:
  labels:
    io.rancher.scheduler.affinity:host_label: name=bbb
  ports:
  - 443/tcp
  - 80/tcp
  environment:
    DB_NAME: aaa
    DB_PASS: aaa
    DB_USER: aaa
  image: my-image/test:latest
  links:
    db: mysql
    redis: redis
```

but when I cat the `/etc/hosts/` file on a container in the `aaa` service, here is what it contains

```bash
172.17.0.10     2943fc46c73a                                                    
127.0.0.1       localhost                                                       
::1     localhost ip6-localhost ip6-loopback                                    
fe00::0 ip6-localnet                                                            
ff00::0 ip6-mcastprefix                                                         
ff02::1 ip6-allnodes                                                            
ff02::2 ip6-allrouters
```
this is on a php-apache instance from docker.  With out the host entry there, it causes PHP to throw `php network getaddresses getaddrinfo failed name or service not known` because it's not in the `/etc/hosts` file.
