### ISSUE TITLE
Docker-compose.yml for Balancers, External Service and Service Alias doesn't work with Rancher-Compose

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#1296]
v0.24.0

In our `docker-compose.yml` file that we produce in Rancher, we provide an image for our balancers, external service and service alias

```
lb:
  image: rancher/load-balancer-service
db:
  image: rancher/external-service
web:
  image: rancher/dns-service
```

If you try to use `rancher-compose` from our exported config, it will not work as these images don't work.
