### ISSUE TITLE
Does volumes-from not work?

### ISSUE THREAD

**Issue by pbecotte** [rancherio/rancher#1353]
I have been trying for a couple of hours to set up a container with a backup data container and failing.  First I tried using rancher-compose.  I get

statusCode [422]. Status [422 status code 422]. Body: [{"id":"a924ba93-d441-4f02-8419-0fbf7a715d93","type":"error","links":{},"actions":{},"status":422,"code":"InvalidReference","message":null,"detail":null,"fieldName":"LaunchConfigName"}] 

from any service that has 'volumes_from:' listed in docker-compose.yml.  Then I tried to use the UI.  I could not actually find a spot in the UI to specify volumes-from.  Another bug ticket was talking about the dropdown under advanced>volumes>volumes-from ... I don't even see that drop down.  

Rancher	v0.24.0
Cattle	v0.56.0
User Interface	v0.28.0

**Comment by sangeethah** [comment]
There is a similar bug - https://github.com/rancherio/rancher/issues/1334 to track the issue for not being able to use volumes-from for services.

Currently UI supports for having "volumes-from" for only containers but not for services. 
For containers , we allow for volumes to be mounted from other containers that are present in the same host as the current container needs to be placed. So UI will expose this option in "Volumes" tab when scheduling option is picked as "run on a specific host" .

**Comment by ibuildthecloud** [comment]
This should work but it's undocumented and the UI doesn't support it.  Volumes-from introduces some challenges when scaling services.  If B does volumes from A what does that mean as you scale up A or B?  To address the ambiguity of this behavior we introduced a concept called sidekicks.  Basically you can only do volumes from if the containers involved have a side kick relationship.  Sidekicks are scaled and scheduled as one unit.  So if A and B are sidekicks they will be always deploys as a pair and the scale will be locked between them.

You use sidekicks with a label.  For example

```yaml
web:
  labels:
    io.rancher.sidekicks: logs,other
  image: nginx

logs:
  volumes-from:
  - web
  image: ...

other:
  image: ...
```

**Comment by ibuildthecloud** [comment]
Right now data only containers must be running.  We will add an option to disable that.  For a quick workaround just run something that never exits.  Something like

```yaml
data:
  image: ubuntu
  command: cat
  stdin_open: true
```

@alena1108 ^^

**Comment by pbecotte** [comment]
Thanks for the answer - I had a feeling it was something that might not be documented yet, especially considering how far it has come in just the last couple weeks.  I will give both of those suggestions a shot!

**Comment by EliSnow** [comment]
@ibuildthecloud, I recognize the `io.rancher.sidekicks` label and `volumes_from` (note the underscore instead of the hyphen mentioned earlier) features are not yet documented, but it appears it matters which container gets the label. I have a service consisting of a node app with an apache frontend and I wanted the two to be sidekicks. When I put the `io.rancher.sidekicks` label on the apache container (using docker-compopse.yml) rancher-compose would freeze up before creating the apache container. Swapping which container had the label seemed to fix the problem.

Any idea on why that is? Is this a bug in rancher-compose?

If it makes any difference the apache container also has a `volumes_from` and a `links` directive to the node container.

**Comment by deniseschannon** [comment]
@EliSnow I commented on #1566, but basically the latest of rancher (v0.28.0) with rancher-compose (v0.2.1), this should work correctly and as expected.

**Comment by tobowers** [comment]
We are seeing a problem where a container is not getting its volumes_from until we delete it and let rancher reschedule it (sidekick relationship is in place)

**Comment by deniseschannon** [comment]
@tobowers Can you provide a sample docker-compose.yml so that I could try and reproduce? I don't have a great `volumes_from` example.

**Comment by tobowers** [comment]
@deniseschannon https://gist.github.com/tobowers/0854e33bc64ae8eb6523 between the 5 data volumes... usually about 3 work and the other 2 don't get associated.

**Comment by deniseschannon** [comment]
Created https://github.com/rancher/rancher/issues/2333 to track @tobowers issue.

**Comment by ibuildthecloud** [comment]
I've seen this also.

**Comment by alena1108** [comment]
@tobowers Fixed in v0.41.0. let me know if you happen to see it again on the latest

**Comment by vmignot** [comment]
Hi @alena1108 
According to this part of the documentation : 
http://docs.rancher.com/rancher/v1.0/zh/rancher-compose/#example-of-sidekicks-in-rancher-compose-multiple-services-using-the-same-service-for-volumesfrom and this ticket, shared data-volumes should work.


But when I run the following docker-compose.yml
```yaml
keys:
  image: generate-keys
  command: /bin/ash
  stdin_open: true
  tty: true

db:
  image: postgres:9.5
  stdin_open: true
  tty: true

server:
  image: server
  stdin_open: true
  tty: true
  labels:
    io.rancher.sidekicks: keys, worker
  ports:
    - "8080:8080"
  links:
    - db
  volumes_from:
    - keys:ro
  command: ./server.sh

worker:
  image: worker
  stdin_open: true
  tty: true
  links:
    - server
  volumes_from:
    - keys:ro
  privileged: true
  command: ./worker.sh
```

I get: 
````bash
➜  project git:(master) ✗ rancher-compose create
INFO[0000] Creating service server
ERRO[0001] Failed Creating server : Bad response statusCode [422]. Status [422 status code 422]. Body: [fieldName=LaunchConfigName, code=InvalidReference] from [http://localhost:8090/v1/services]
ERRO[0001] Failed to start: server : Bad response statusCode [422]. Status [422 status code 422]. Body: [fieldName=LaunchConfigName, code=InvalidReference] from [http://localhost:8090/v1/services]
FATA[0001] Bad response statusCode [422]. Status [422 status code 422]. Body: [fieldName=LaunchConfigName, code=InvalidReference] from [http://localhost:8090/v1/services]
````

Versions I'm using are the following
Rancher 	v1.1.0-dev5
Cattle 	v0.164.1
User Interface 	v1.1.10
Rancher Compose 	v0.8.4


The use-case here is keys creating ssh-key and then, lets the server and the worker mounts the volumes so they can communicate together with those keys.

Regards,

Victor
