### ISSUE TITLE
rancher-compose links not configured correctly on container

### ISSUE THREAD

**Issue by LyndonHook** [rancherio/rancher#1391]
rancher v0.25.0
rancher-compose v0.1.3

Link two containers using docker-compose.yml
```
nginx:
  image: nginx:1.9.2
  ports:
  - "80:80"
  - "443:443"
  links:
  - php-fpm
php-fpm:
  image: php:5.5-fpm
  ports:
  - "9000:9000"
```

After runninng Docker inspect on the nginx container, based on the documentation link below, all environment variables are set correctly but the `HostConfig.Links` value is null.

https://docs.docker.com/userguide/dockerlinks/#communication-across-links

Expected rancher-compose to function as docker-compose is documented to run.
